version: '3.9'

services:
  echo-service:
    image: alpine:latest
    command: >
      /bin/sh -c 'echo "Var1: $VAR1, Var2: $VAR2, Var3: $VAR3"'
    env_file:
      - env_file1.env
      - env_file2.env
      - env_file3.env
